### ISSUE TITLE
Add ability to select multiple recipes

### ISSUE THREAD

**Issue by RuPaulogize** [samdrudd/matcalc#1]

**Comment by samdrudd** [comment]
Show multiple on screen somehow
- multiple tabs
- make text / icons smaller
- collapse recipe if other is expanded

**Comment by samdrudd** [comment]
I think we can separate the window into 4 'panes' or columns and you can select up to 4 recipes at a time OR you can select more than 4 and you have to scroll

**Comment by samdrudd** [comment]
We now store selected recipes in an array and just iterate through it to display each recipe in its own column.

Implemented in commit 7f77584d1e7ca0c458da0e0349d98df7896bed4d

Closing.
